// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHscwnaRgFrL_oe-omZQL09XWBCz2VjQA',
    appId: '1:661235988478:web:ef305a4056d2f94192b2af',
    messagingSenderId: '661235988478',
    projectId: 'flutter-movie-app-c1275',
    authDomain: 'flutter-movie-app-c1275.firebaseapp.com',
    storageBucket: 'flutter-movie-app-c1275.appspot.com',
    measurementId: 'G-GYLTN0RE7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEs4MPD1QHGpYcnLJJc0r_GBpi84NY5E8',
    appId: '1:661235988478:android:f26350333a70907e92b2af',
    messagingSenderId: '661235988478',
    projectId: 'flutter-movie-app-c1275',
    storageBucket: 'flutter-movie-app-c1275.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNW8nlJ1J6KyPt8wJZN5qEZMI_-XbpYt0',
    appId: '1:661235988478:ios:a78d9d873d43268692b2af',
    messagingSenderId: '661235988478',
    projectId: 'flutter-movie-app-c1275',
    storageBucket: 'flutter-movie-app-c1275.appspot.com',
    iosBundleId: 'com.example.flutterMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNW8nlJ1J6KyPt8wJZN5qEZMI_-XbpYt0',
    appId: '1:661235988478:ios:a78d9d873d43268692b2af',
    messagingSenderId: '661235988478',
    projectId: 'flutter-movie-app-c1275',
    storageBucket: 'flutter-movie-app-c1275.appspot.com',
    iosBundleId: 'com.example.flutterMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHscwnaRgFrL_oe-omZQL09XWBCz2VjQA',
    appId: '1:661235988478:web:5f453c5dc0e0a60f92b2af',
    messagingSenderId: '661235988478',
    projectId: 'flutter-movie-app-c1275',
    authDomain: 'flutter-movie-app-c1275.firebaseapp.com',
    storageBucket: 'flutter-movie-app-c1275.appspot.com',
    measurementId: 'G-TJJJGVY8C6',
  );
}
